# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '17.5'

target 'BookWatchman' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookWatchman
  pod 'GoogleMLKit/TextRecognition', '7.0.0'

  target 'BookWatchmanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookWatchmanUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
end
